version: "3"
services:
  ngrok-tails-server:
    image: wernight/ngrok
    networks:
      - issuer_kit
    ports:
      - 4044:4040
    command: ngrok http tails-server:6543 --log stdout
  tails-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.tails-server
    ports:
      - 6543:6543
    networks:
      - issuer_kit
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path $STORAGE_PATH
        --log-level $LOG_LEVEL
  tester:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
networks:
  issuer_kit:
